export const ACTIONS = {
  GET_POSTS: "GET_POSTS",
  GET_POST_DETAILS: "GET_POST_DETAILS",
  GET_FAVORITES: "GET_FAVORITES",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CHATS: "GET_CHATS",
  GET_CHAT_DETAILS: "GET_CHAT_DETAILS",
}

export const API = "https://tektonik.herokuapp.com/"